# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # HHVM
  - hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer update

script: vendor/bin/phpspec run
